version: "3.8"

services:
  splunk:
    image: splunk/splunk:9.2
    container_name: splunk
    env_file:
      - .env
    ports:
      - "8002:8000" # splunk ui
      - "8088:8088" # HEC
    networks:
      - cashflow-network

networks:
  cashflow-network:
    external: true
