version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: cashflow-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - cashflow-network

  backend:
    image: cashflow-backend:1.0
    container_name: cashflow-backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    env_file:
      - ../app/server/.env
    restart: unless-stopped
    networks:
      - cashflow-network

  frontend:
    build:
      context: ../app/client
      args:
        VITE_BACKEND_API: http://localhost:8000
    image: cashflow-frontend:1.0
    container_name: cashflow-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - cashflow-network

volumes:
  mongo_data:

networks:
  cashflow-network:
    external: true
